# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bb61da435c8c889fe3926005d9f49f9314af28c6a6b0cd1c747dddf5dfc0af67a301c2e200ac32c95228dd6df4b2d8b7c3bf52267dd13c67053c401ac5d27c7

test:
  secret_key_base: 7fb234bd6e614576d328bf9d31b5bfa140baddb7edebc89b23fa0aa78fb0cc77f612d13b9b4b86d15fbf4bbdae5f96654191fcd2f66600ccd63f8bc8262e1abc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
